-- PROJECT
-- TABLE
CREATE TABLE ENT(					--소속사
ENT_CODE number(3), 				--기업코드 (PK)
ENT_NAME VARCHAR2(100) NOT NULL, 	--기업명
TEL nVARCHAR2(100),					--대표연락번호
CEO NVARCHAR2(100),					--대표이사
ADDRESS VARCHAR2(100),				--주소
F_DATE NUMBER(4),					--설립년도
PRIMARY KEY(ENT_CODE)
);

CREATE TABLE G_GROUP(
ENT_CODE NUMBER(3),					--기업코드 (FK)
TEAM_NAME NVARCHAR2(100),			--팀명(PK)
MEMBER_CNT number(2),				--멤버수
D_SONG NVARCHAR2(100),				--데뷔곡
D_DATE DATE,						--데뷔일
F_NAME NVARCHAR2(100),				--팬덤
LEADER NVARCHAR2(100),				--리더
PRIMARY KEY(TEAM_NAME),
FOREIGN KEY(ENT_CODE) REFERENCES ENT(ENT_CODE)
);

CREATE TABLE ALB(					--앨범
ALB_CODE NVARCHAR2(100),			--앨범코드 (PK)
TEAM_NAME NVARCHAR2(100),			--팀이름(FK)
ALB_NAME NVARCHAR2(100),			--앨범명
SONG_CNT NUMBER(3),					--수록곡수
T_SONG NVARCHAR2(100),				--타이틀곡
S_DATE DATE,						--발매일
PRIMARY KEY(ALB_CODE),
FOREIGN KEY(TEAM_NAME) REFERENCES G_GROUP(TEAM_NAME)
);

CREATE TABLE SINGER(				--가수
NUM_SEQ NVARCHAR2(100),				--구분번호(PK)
NAME NVARCHAR2(100),				--이름
BIRTH DATE,							--생년월일
NAT NVARCHAR2(100),					--국적
TEAM_NAME NVARCHAR2(100),			--팀이름(FK)
PART NVARCHAR2(100),				--담당파트
SNS NVARCHAR2(100),					--sns
PRIMARY KEY(NUM_SEQ),
FOREIGN KEY(TEAM_NAME) REFERENCES G_GROUP(TEAM_NAME)
);

DROP TABLE SINGER ;
DROP TABLE G_GROUP  ;
DROP TABLE ENT ;
DROP TABLE ALB;


