--원하는 컬럼만 출력하기
CREATE TABLE ANIMAL_INS(
    ANIMAL_ID VARCHAR(10)NOT NULL,
    ANIMAL_TYPE VARCHAR(10)NOT NULL,
    DATETIME DATE NOT NULL,
    INTAKE_CONDITON VARCHAR(10)NOT NULL,
    NAME VARCHAR(15),    
    SEX_UPON_INTAKE VARCHAR(20) NOT NULL
);
DROP TABLE ANIMAL_INS ;
INSERT INTO ANIMAL_INS(ANIMAL_ID, ANIMAL_TYPE, DATETIME, INTAKE_CONDITON, NAME, SEX_UPON_INTAKE)
VALUES ('A50005','Dog','2013-10-14','Normal','Diablo','Neutered Male');
INSERT INTO ANIMAL_INS(ANIMAL_ID, ANIMAL_TYPE, DATETIME, INTAKE_CONDITON, NAME, SEX_UPON_INTAKE)
VALUES ('A50000','Dog','2013-10-23','Sick','Miller','Intact Male');
INSERT INTO ANIMAL_INS(ANIMAL_ID, ANIMAL_TYPE, DATETIME, INTAKE_CONDITON, NAME, SEX_UPON_INTAKE)
VALUES ('A50003','Dog','2013-11-03','Aged','Minnie','Spayed Female');
INSERT INTO ANIMAL_INS(ANIMAL_ID, ANIMAL_TYPE, DATETIME, INTAKE_CONDITON, NAME, SEX_UPON_INTAKE)
VALUES ('A50002','Dog','2013-11-18','Sick','Cherokee','Spayed Female');
INSERT INTO ANIMAL_INS(ANIMAL_ID, ANIMAL_TYPE, DATETIME, INTAKE_CONDITON, NAME, SEX_UPON_INTAKE)
VALUES ('A50001','Dog','2013-11-18','Normal','Jackie','Spayed Female');

SELECT ANIMAL_ID , NAME FROM ANIMAL_INS ORDER BY ANIMAL_ID ;


