--모든 레코드 조회하기
CREATE TABLE ANIMAL_INS(
    ANIMAL_ID VARCHAR(10)NOT NULL,
    ANIMAL_TYPE VARCHAR(10)NOT NULL,
    DATETIME DATE NOT NULL,
    INTAKE_CONDITON VARCHAR(10)NOT NULL,
    NAME VARCHAR(15),    
    SEX_UPON_INTAKE VARCHAR(20) NOT NULL
);
INSERT INTO ANIMAL_INS(ANIMAL_ID, ANIMAL_TYPE, DATETIME, INTAKE_CONDITON, NAME, SEX_UPON_INTAKE)
VALUES ('A399552','Dog','2013-10-14','Normal',NULL,'Neutered Male');
INSERT INTO ANIMAL_INS(ANIMAL_ID, ANIMAL_TYPE, DATETIME, INTAKE_CONDITON, NAME, SEX_UPON_INTAKE)
VALUES ('A379998','Dog','2013-10-23','Normal','Sam','Intact Male');
INSERT INTO ANIMAL_INS(ANIMAL_ID, ANIMAL_TYPE, DATETIME, INTAKE_CONDITON, NAME, SEX_UPON_INTAKE)
VALUES ('A370852','Dog','2013-11-03','Normal','Sam','Spayed Female');
INSERT INTO ANIMAL_INS(ANIMAL_ID, ANIMAL_TYPE, DATETIME, INTAKE_CONDITON, NAME, SEX_UPON_INTAKE)
VALUES ('A403564','Dog','2013-11-18','Normal','Sweetie','Spayed Female');

SELECT * FROM ANIMAL_INS ORDER BY ANIMAL_ID;